### PR TITLE
Class test

### PR DESCRIPTION
**Pull request by EvanGudmestad**

### CODE REVIEW

**Comment by malkurwi** [comment]
Hey!

**Comment by malkurwi** [comment]
Can you hear me!

**Comment by crazzei** [comment]
hello

**Comment by malkurwi** [comment]
hello, crazzei

**Comment by Akrugerus** [comment]
I approve this commit

**Comment by crazzei** [comment]
i dont understand

**Comment by ToddSisson** [comment]
10/10

**Comment by crazzei** [comment]
would commit again

**Comment by malkurwi** [comment]
me no Ennglish amigos!

**Pull request closed without merging**
